spring.application.name=projetocorridas

server.servlet.context-path=/projeto
spring.datasource.url=jdbc:postgresql://localhost:5432/pweb2
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
jwt.secret=projetocorridas
jwt.expiration-seconds=2800

